spring:
  application:
    name: macaronsBackend
  datasource:
      url: jdbc:postgresql://localhost:5234/macaronsdb
      username: user # local database instead of container version is macaron
      password: password # macaron


logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
    fr:
      clementjaminion:
        macaronsbackend: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
